#!/usr/bin/env python3
"""
Audit which animation .glb files are referenced by AnimationRegistry but
missing from disk. Writes a manifest to MISSING_ANIMS.md at the repo
root. Re-run after dropping new .glb files into assets/animations/.

Usage: python3 scripts/anim/audit_anim_assets.py

Reads:  scripts/anim/animation_registry.gd
Writes: MISSING_ANIMS.md  (overwritten)

Why this exists: T-pose mobs in the dojo turned out to be empty
animation folders on disk. The loader's silent fallback chain hid the
problem. This audit makes "what assets do I need to drop?" a
single-command answer instead of a play-and-find-out.
"""
import re
from pathlib import Path
from collections import defaultdict

ROOT = Path(__file__).resolve().parent.parent.parent  # marduk/
REG_PATH = ROOT / "scripts/anim/animation_registry.gd"
ASSETS_ROOT = ROOT / "assets/animations"
MANIFEST = ROOT / "MISSING_ANIMS.md"

reg = REG_PATH.read_text()

# Pull every quoted .glb path string from the registry.
paths = set()
for m in re.finditer(r'"([a-z0-9_/]+\.glb)"', reg, re.IGNORECASE):
    paths.add(m.group(1))

missing_shared = []
missing_mob = []
missing_boss = []
mob_block = reg[reg.find("const MOB_SLOTS"):reg.find("const BOSS_SLOTS")]

for p in sorted(paths):
    abs_path = ASSETS_ROOT / p
    if abs_path.exists():
        continue
    if p.startswith("shared/"):
        missing_shared.append(p)
    elif p in mob_block:
        missing_mob.append(p)
    else:
        missing_boss.append(p)

mob_groups: dict = defaultdict(list)
for p in missing_mob:
    mob_groups[p.split("/")[0]].append(p)
boss_groups: dict = defaultdict(list)
for p in missing_boss:
    boss_groups[p.split("/")[0]].append(p)

total_missing = len(missing_shared) + len(missing_mob) + len(missing_boss)
print(f"Missing: {total_missing} of {len(paths)} (shared={len(missing_shared)} mobs={len(missing_mob)} bosses={len(missing_boss)})")

out = [
    "# Missing Animation Assets",
    "",
    "Generated by `scripts/anim/audit_anim_assets.py`. Re-run after dropping new .glb files.",
    "",
    f"**Total missing:** {total_missing} of {len(paths)} declared paths",
    f"- Shared (highest priority, every character uses these): {len(missing_shared)}",
    f"- Mob-specific: {len(missing_mob)}",
    f"- Boss-specific: {len(missing_boss)}",
    "",
    "Missing anims fall back to the shared slot or the mesh's embedded library; if BOTH miss, mobs T-pose. EnemyBase.gd's alias chain now includes embedded Mixamo names as a final safety net so even with no real anims they play SOMETHING.",
    "",
    "---",
    "",
    "## Shared",
    "",
    "Drop into `assets/animations/shared/<subfolder>/`. These are used by every character (player + mobs + bosses + NPCs) so they have outsized impact.",
    "",
]
out.extend([f"- `assets/animations/{p}`" for p in missing_shared])
out.append("")
out.append("## Mobs")
out.append("")
out.append("Drop into `assets/animations/mobs/<mob_id>/`. Each missing file means that mob falls back to a shared anim or T-poses.")
out.append("")
for mob in sorted(mob_groups.keys()):
    out.append(f"### `{mob}/`")
    out.extend([f"- `assets/animations/{p}`" for p in mob_groups[mob]])
    out.append("")
out.append("## Bosses")
out.append("")
out.append("Drop into `assets/animations/bosses/<boss_id>/`. Boss-specific attack patterns reference these via boss_attack_pattern.gd; missing means the pattern fires with no telegraph anim (just the floor decal).")
out.append("")
for boss in sorted(boss_groups.keys()):
    out.append(f"### `{boss}/`")
    out.extend([f"- `assets/animations/{p}`" for p in boss_groups[boss]])
    out.append("")
MANIFEST.write_text("\n".join(out))
print(f"Wrote: {MANIFEST}")
